### ISSUE TITLE
Setting session before login throws `Error: Can’t set headers after they are sent`

### ISSUE THREAD

**Issue by Yuripetusko** [koajs/session#89]
I need to have `sessionId` even before user logs in, to tracks browsing session of user and tie him to it later when he logs in, so I did this:

```
server.use(async (ctx, next) => {
  if (!ctx.session.sessionId) {
    ctx.session.sessionId = uuid.v4();
  }
  await next();
});
```

however if I do this I get (despite session id saving no problem)

```
{ Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:504:11)
    at ServerResponse.setHeader (_http_outgoing.js:511:3)
    at Cookies.set (/Users/yuri/Sites/bridebook/Bridebook-next/node_modules/cookies/index.js:115:13)
    at ContextSession.save (/Users/yuri/Sites/bridebook/Bridebook-next/node_modules/koa-session/lib/context.js:276:22)
    at ContextSession.commit (/Users/yuri/Sites/bridebook/Bridebook-next/node_modules/koa-session/lib/context.js:220:16)
    at session (/Users/yuri/Sites/bridebook/Bridebook-next/node_modules/koa-session/index.js:46:18)
    at <anonymous> headerSent: true }

```

Any idea what I am doing wrong?

**Comment by davegomez** [comment]
I'm getting the exact same error when trying to use koa-session + Next.js with async/await functions.

This is the code I have to write a UUID in the session:

```
    router.get('/', async ctx => {
      ctx.session.uuid = ctx.session.uuid || uuidv4()
      const params = { uuid: ctx.session.uuid }
      await app.render(ctx.req, ctx.res, '/', params)
      ctx.respond = false
    })
```

I get the error even if I use it just as a middleware (without routing) unless I write the function as not async.

**Comment by Yuripetusko** [comment]
@davegomez yes we are on nextJS also

**Comment by dead-horse** [comment]
koa will send body when all middleware executed. but next.js is not follow this rule for now, it will send body before middleware executed, so when middleware's downstream try to set a header, it will throw this error.

**Comment by davegomez** [comment]
Any idea how to workaround this @dead-horse?

@timneutkens from Next.js is already looking at the issue.

**Comment by dead-horse** [comment]
there are lot's of middlewares will not work with next.js if it still use `ctx.respond = false`, for now, you can't set session in the same controller with next.js.

**Comment by coler-j** [comment]
@dead-horse which version? I am on `2.13.0` (the current version) and this is still happening.
